import BoneSaw from "./BoneSaw.jpeg"
import SurgicalScissors from "./SurgicalScissors.jpeg"
import Scalpel from "./Scalpel.jpeg"
import Forceps from "./Forceps.jpeg"
import Retractor from "./Retractor.jpeg"
import SurgicalNeedleHolder from "./SurgicalNeedleHolder.jpeg"
import SurgicalClamp from "./SurgicalClamp.jpeg"
import Speculum from "./Speculum.jpeg"
import SurgicalDrill from "./SurgicalDrill.jpeg"
import ElectrosurgicalPencil from "./ElectrosurgicalPencil.jpeg"
import Hemostat from "./Hemostat.jpeg"
import Trocars from "./Trocars.jpeg"
import Curette from "./Curette.png"
import Dilator from "./Dilator.jpeg"
import SurgicalMask from "./SurgicalMask.jpeg"
import SurgicalDrapes from "./SurgicalDrapes.jpeg"
import SurgicalGown from "./SurgicalGown.jpeg"
import ContaAngles from "./ContaAngles.jpeg"
import Proctoscope from "./Proctoscope.jpeg"
import Tourniquet from "./Tourniquet.jpeg"
import Laparoscope from "./Laparoscope.jpeg"



export const assets = {
  BoneSaw, SurgicalScissors, Scalpel, Forceps, Retractor, SurgicalNeedleHolder,
  SurgicalClamp, Speculum, SurgicalDrill, ElectrosurgicalPencil, Hemostat,
  Trocars, Curette, Dilator, SurgicalMask, SurgicalDrapes, SurgicalGown, ContaAngles,
  Tourniquet, Proctoscope,Laparoscope
};




export const manageDate = [
  {
    assetID: "ASSET-1",
    assetName: "Surgical Scissors",
    description: "Used for precise cutting during surgery.",
    image: assets.SurgicalScissors,
    type: "Tool",
    aseetStatus: "Available",
    category: "Cutting Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Tissue cutting",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-2",
    assetName: "Scalpel",
    description: "Sharp instrument for making incisions.",
    image: assets.Scalpel,
    aseetStatus: "Available",
    category: "Cutting Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Incision making",
    urgency: "High",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-3",
    assetName: "Forceps",
    description: "Used for grasping or holding tissues.",
    image:assets.Forceps,
    type: "Tool",
    aseetStatus: "Available",
    category: "Grasping Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Tissue manipulation",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-4",
    assetName: "Retractor",
    description: "Holds back tissues during surgery.",
    image:assets.Retractor,
    type: "Tool",
    aseetStatus: "Available",
    category: "Retracting Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Exposure maintenance",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-5",
    assetName: "Surgical Needle Holder",
    description: "Used to hold suturing needles.",
    image:assets.SurgicalNeedleHolder,
    type: "Tool",
    aseetStatus: "Available",
    category: "Suturing Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Wound closure",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-6",
    assetName: "Surgical Clamp",
    description: "Used to control bleeding.",
    image:assets.SurgicalClamp,
    type: "Tool",
    aseetStatus: "Available",
    category: "Clamping Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Bleeding control",
    urgency: "High",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-7",
    assetName: "Speculum",
    description: "Used for opening a body cavity.",
    image:assets.Speculum,
    type: "Tool",
    aseetStatus: "Available",
    category: "Examination Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Cavity access",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-8",
    assetName: "Bone Saw",
    description: "Used for cutting bones.",
    image:assets.BoneSaw,
    type: "Tool",
    aseetStatus: "Available",
    category: "Cutting Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Bone cutting",
    urgency: "High",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-9",
    assetName: "Surgical Drill",
    description: "h",
    image:assets.SurgicalDrill,
    type: "Tool",
    aseetStatus: "Available",
    category: "Cutting Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Bone drilling",
    urgency: "High",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-10",
    assetName: "Laparoscope",
    description: "Used in minimally invasive surgery.",
    image:assets.Laparoscope,
        type: "Tool",
    aseetStatus: "Available",
    category: "Visualization Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Internal visualization",
    urgency: "High",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-11",
    assetName: "Surgical Drapes",
    description: "Maintains a sterile field.",
    image:assets.SurgicalDrapes,
    type: "Supply",
    aseetStatus: "Available",
    category: "Sterile Barrier",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Infection control",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-12",
    assetName: "Electrosurgical Pencil",
    description: "Used for cutting/coagulating tissue.",
    image:assets.ElectrosurgicalPencil,
    type: "Tool",
    aseetStatus: "Available",
    category: "Electrosurgical Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Tissue cutting/coagulation",
    urgency: "High",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-13",
    assetName: "Hemostat",
    description: "Used to stop bleeding.",
    image:assets.Hemostat,
    type: "Tool",
    aseetStatus: "Available",
    category: "Clamping Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Bleeding control",
    urgency: "High",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-14",
    assetName: "Trocars",
    description: "Used for draining fluids.",
    image:assets.Trocars,
    type: "Tool",
    aseetStatus: "Available",
    category: "Access Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Fluid drainage",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-15",
    assetName: "Curette",
    description: "Used for scraping tissue.",
    image:assets.Curette,
    type: "Tool",
    aseetStatus: "Available",
    category: "Scraping Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Tissue removal",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-16",
    assetName: "Dilator",
    description: "Used to widen body passages.",
    image:assets.Dilator,
    type: "Tool",
    aseetStatus: "Available",
    category: "Expansion Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Passage widening",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-17",
    assetName: "Proctoscope",
    description: "Used for rectal examination.",
    image:assets.Proctoscope,
    type: "Tool",
    aseetStatus: "Available",
    category: "Examination Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Rectal examination",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-18",
    assetName: "Tourniquet",
    description: "Controls blood flow.",
    image:assets.Tourniquet,
    type: "Tool",
    aseetStatus: "Available",
    category: "Compression Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Blood flow control",
    urgency: "High",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-19",
    assetName: "Surgical Mask",
    description: "Protects against contamination.",
    image:assets.SurgicalMask,
    aseetStatus: "Available",
    category: "Protective Equipment",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Infection control",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-20",
    assetName: "Surgical Gown",
    description: "Worn by surgeons for sterility.",
    image:assets.SurgicalGown,
    type: "Supply",
    aseetStatus: "Available",
    category: "Protective Equipment",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Important",
    systemRole: "Infection control",
    urgency: "Normal",
    region: "North Wing OR1",
  },
  {
    assetID: "ASSET-21",
    assetName: "Conta Angles",
    description:
      "contra angle surgical handpiece is an essential tool in complex dental surgeries",
    image:assets.ContaAngles,
    type: "Tool",
    aseetStatus: "Available",
    category: "Dental Tool",
    serialNumber: "Kk-705535",
    manfacturer: "Exacto Surgical",
    company: "City Hospital",
    impact: "Critical",
    systemRole: "Dental procedures",
    urgency: "High",
    region: "North Wing OR1",
  },
];
